#!/bin/bash
# Author:	Pedro Valero
#
# Imdea
# 2015-02-23
TMP="tmp.yml"
FULL_TEMPLATE="full_template.html"
BODY="body_template"
BEGIN="begin"
VARS="d3_vars"

if [ $# -eq 0 ] || [ $# -eq 1 ]
	then
	echo "Usage: ./generate_graphs.sh [output] [data_files]"
	echo "Plots in [output] the graphs related to [data files]"
	echo "The data files should have been generated by mist or have the same format"
	exit
fi

OUTPUT=$1
FILES=${@:2}
i=1

echo "Starting template..."
cat $BEGIN $VARS > $FULL_TEMPLATE
echo "" >> $FULL_TEMPLATE

echo "Preparing temporal yml file..."
for file in $FILES
do
	echo "---" >> $TMP
	echo "graph: graph$i" >> $TMP
	echo "file: $file" >> $TMP
	echo "svg: svg$i" >> $TMP
	echo "<div id=\"graph$i\"></div>" >> $FULL_TEMPLATE
	echo "" >> $FULL_TEMPLATE
	i=`expr $i + 1`
done

echo "---" >> $TMP

echo "Building full template..."

cat $TMP $FULL_TEMPLATE | mustache > $OUTPUT

