#!/bin/bash
# Author:	Pedro Valero
#
# Imdea
# 2015-02-23
TMP="tmp.yml"
BODY="body_template"
BEGIN="begin"
VARS="d3_vars"

if [ $# -eq 0 ] || [ $# -eq 1 ]
	then
	echo "Usage: ./generate_graphs.sh [output] [data_files]"
	echo "Generates a folder with the name [output] which contains the [data_files] and an [output].html with the graphs related to [data_files]"
	echo "The data files should have been generated by mist or have the same format"
	echo "This scripts needs mustache to be installed"
	exit
fi


OUTPUT=$1
FILES=${@:2}
i=1


echo "Creating dir $OUTPUT"
mkdir $OUTPUT

OUT_FILE="$OUTPUT/$OUTPUT.html"

cat $BEGIN  > $OUT_FILE

echo "Coping data files"
for file in $FILES
do
	echo "<div id=\"graph$i\"></div>" >> $OUT_FILE
	base=${file##*/}
	cp $file $OUTPUT/$base
	i=`expr $i + 1`
done

cat $VARS >> $OUT_FILE

echo "" >> $OUT_FILE

echo "Building temporal yml file..."
echo "{ \"translator\" :[" >> $TMP

i=1

for file in $FILES
do
	echo "{\"graph\": \"graph$i\", \"file\": \"${file##*/}\", \"svg\": \"svg$i\"}" >> $TMP
	if [ $i -lt $(($# -1)) ]
		then
		echo "," >> $TMP
	fi
	echo "" >> $OUT_FILE
	i=`expr $i + 1`
done

echo "]}" >> $TMP

echo "Building final document..."

cat $TMP | mustache - $BODY >> $OUT_FILE

echo "Removing temporal files..."
rm $TMP

