#!/bin/bash
# Author:	Pedro Valero
#
# Imdea
# 2015-02-23
TMP="tmp.yml"
BODY="body_template"
BEGIN="begin"
VARS="d3_vars"

if [ $# -eq 0 ] || [ $# -eq 1 ]
	then
	echo "Usage: ./generate_graphs.sh [output] [data_files]"
	echo "Plots in [output] the graphs related to [data files]"
	echo "The data files should have been generated by mist or have the same format"
	exit
fi

OUTPUT=$1
FILES=${@:2}
i=1

cat $BEGIN  > $OUTPUT

for file in $FILES
do
	echo "<div id=\"graph$i\"></div>" >> $OUTPUT
	i=`expr $i + 1`
done

cat $VARS >> $OUTPUT

echo "" >> $OUTPUT

echo "Preparing temporal yml file..."
echo "{ \"translator\" :[" >> $TMP

i=1

for file in $FILES
do
	echo "{\"graph\": \"graph$i\", \"file\": \"$file\", \"svg\": \"svg$i\"}" >> $TMP
	if [ $i -lt $(($# -1)) ]
		then
		echo "," >> $TMP
	fi
	echo "" >> $OUTPUT
	i=`expr $i + 1`
done

echo "]}" >> $TMP

echo "Building final document..."

cat $TMP | mustache - $BODY >> $OUTPUT

echo "Removing temporal files..."
rm $TMP

